2019-04-03 12:31:27,583 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-03 12:31:50,249 ERROR: Exception on /edit_profile [POST] [in /home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "ix_user_username"
DETAIL:  Key (username)=(finn) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/obi-wan/pyweb/app/routes.py", line 123, in edit_profile
    db.session.commit()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 978, in _emit_update_statements
    statement, multiparams
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/obi-wan/pyweb/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_user_username"
DETAIL:  Key (username)=(finn) already exists.

[SQL: UPDATE "user" SET username=%(username)s, about_me=%(about_me)s WHERE "user".id = %(user_id)s]
[parameters: {'username': 'finn', 'about_me': 'the most powerfull mistborn ever', 'user_id': 4}]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-04-03 12:45:21,436 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-03 14:30:16,718 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-03 14:31:10,383 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-03 17:50:07,982 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-03 17:50:23,218 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:45:44,884 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:46:34,812 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:47:59,977 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:48:41,858 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:49:27,987 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:50:06,409 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:50:18,076 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:50:49,974 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:52:22,631 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:54:42,386 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:55:26,586 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:57:43,391 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:58:49,261 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:59:13,554 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 12:59:53,675 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:00:05,133 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:00:13,795 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:01:31,658 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:03:43,509 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:04:05,662 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:04:38,499 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:05:08,762 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:05:34,184 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:06:03,688 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:08:27,964 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:08:43,369 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:09:22,255 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:10:27,021 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 13:14:06,291 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 19:44:44,151 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 19:45:04,572 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 19:45:50,382 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 19:59:21,345 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
2019-04-04 20:54:55,410 INFO: Microblog startup [in /home/obi-wan/pyweb/app/__init__.py:29]
